//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceTimeManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaceTimeManagerEntities : DbContext
    {
        public RaceTimeManagerEntities()
            : base("name=RaceTimeManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RaceEntry> RaceEntries { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Runner> Runners { get; set; }
        public virtual DbSet<Split> Splits { get; set; }
        public virtual DbSet<StartFinishTime> StartFinishTimes { get; set; }
    }
}
