//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceTimeManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaceEntry()
        {
            this.Splits = new HashSet<Split>();
        }
    
        public int RaceID { get; set; }
        public int BibNumber { get; set; }
        public Nullable<int> RunnerID { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Runner Runner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Split> Splits { get; set; }
        public virtual StartFinishTime StartFinishTime { get; set; }
    }
}
